Removed Dates and Update Status for Continuous Journal
deep-learning-indaba/Baobab pull request #1091
Opened 2023-02-28 15:07 UTC by shreyalpandit

Addresses Issue #1090 so that the continuous journal does not have a value for all dates except start date.

2023-03-05 09:42 UTC, avishkar58 commented
Hey @amritpurshotam would you mind reviewing this PR please?

2023-03-05 19:01 UTC, amritpurshotam requested changes
Nice work @shreyalpandit !. Just some small changes to clean up the Event construction and some optional changes for each of the `@property` fields. Otherwise looks good :)

2023-03-06 08:05 UTC, shreyalpandit commented on api/app/events/models.py
> +        self.registration_close = None if event_type == EventType.CONTINUOUS_JOURNAL else registration_close
That makes sense! I was also thinking of tracking continuous events after defining the event type enum:

```
continuous_event =
{
    EventType.EVENT: False,
    EventType.AWARD: False,
    EventType.CALL: False,
    EventType.PROGRAMME: False,
    EventType.JOURNAL: False,
    EventType.CONTINUOUS_JOURNAL: True
}
```

and then making a subclass of `Event` called `ContinuousEvent` for now that sets the dates to None. 
```
class ContinuousEvent(Event):
    def __init__(self,
                names,
                descriptions,
                start_date,
                key,
                organisation_id,
                email_from,
                url,
                event_type,
                travel_grant,
                miniconf_url=None):
        super().__init__(self,
                        names=names,
                        descriptions=descriptions,
                        start_date=start_date,
                        end_date=None,
                        key=key,
                        organisation_id=organisation_id,
                        email_from=email_from,
                        url=url,
                        application_open=None, ...)
        
    def update(...):
       ...
```

When future event types are added, they can be marked as continuous events or not, and the rest can stay the same?

2023-03-22 20:26 UTC, amritpurshotam commented on api/app/events/models.py
> +    return True
I like this, much much cleaner than what I suggested!

2023-03-22 21:47 UTC, merged