Add IndabaX ZA organisation
deep-learning-indaba/Baobab pull request #1120
Opened 2023-04-30 19:12 UTC by amritpurshotam

2023-05-05 08:26 UTC, avishkar58 requested changes

2023-05-05 08:26 UTC, avishkar58 commented on api/migrations/versions/0462d1a06d40_add_indabax_za_organisation.py
> +    aims = Organisation(
indabax, not aims :)

2023-05-05 11:27 UTC, amritpurshotam commented on api/migrations/versions/0462d1a06d40_add_indabax_za_organisation.py
> +    aims = Organisation(
😅 fixed it now

2023-05-06 13:29 UTC, avishkar58 approved these changes

2023-05-06 13:29 UTC, merged