Iss598
deep-learning-indaba/Baobab pull request #763
Opened 2020-09-04 07:08 UTC by greeffjean

Replaced table with Bootstrap column

2020-09-05 11:54 UTC, avishkar58 requested changes

2020-09-05 11:54 UTC, avishkar58 commented on webapp/src/pages/home/Home.js
> +                <div class="row event-table">
className (also in the divs below)

2020-09-05 11:56 UTC, avishkar58 commented
Hi Jean,
Thanks for this change. 
Can you please make your PR names more meaningful - it's hard to keep track of "Iss698000" "Iss731" etc and this one has nothing to do with issue 598 anyway

2020-09-07 08:52 UTC, greeffjean commented
Sorry I see I made this mistake by confusing this issue with another
branch, Do you mean by PR names the branch naming on my PC for
instance iss731 ect?

On Sat, Sep 5, 2020 at 1:57 PM Avishkar Bhoopchand <notifications@github.com>
wrote:

> Hi Jean,
> Thanks for this change.
> Can you please make your PR names more meaningful - it's hard to keep
> track of "Iss698000" "Iss731" etc and this one has nothing to do with issue
> 598 anyway
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/deep-learning-indaba/Baobab/pull/763#issuecomment-687599576>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKXI6XDIB3LWXANPVC4P6IDSEIRRBANCNFSM4QXPO5DA>
> .
>

2020-10-19 20:16 UTC, merged