Iss787
deep-learning-indaba/Baobab pull request #795
Opened 2020-10-12 18:43 UTC by greeffjean

Please review, tag filtering functionality added, Tag API service created. List UI updated

2020-10-18 20:55 UTC, avishkar58 commented
Hi Jean,
Thanks for this, I'll review it after your previous PRs have been merged so theres a clean diff

2020-10-19 07:13 UTC, greeffjean commented
Hi Avishkar.

Thank you for the payment, did you have a little break / holiday?

Can you please assign me a new issue in the mean time?

Have a great day!
Kind Regards

Jean Greeff

On Sun, Oct 18, 2020 at 10:55 PM Avishkar Bhoopchand <
notifications@github.com> wrote:

> Hi Jean,
> Thanks for this, I'll review it after your previous PRs have been merged
> so theres a clean diff
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/deep-learning-indaba/Baobab/pull/795#issuecomment-711421696>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKXI6XBIN375HWAJG4LXLULSLNI35ANCNFSM4SNFNJSQ>
> .
>

2020-10-29 16:34 UTC, avishkar58 commented
Hi @greeffjean please merge develop in here and resolve any conflicts then I can review :)

2020-10-29 22:15 UTC, avishkar58 requested changes
Hi Jean,

Great work! I really like what you did with the tag selection UI! Two suggestions to improve the UI a bit:
1. I initially found the Update button on the tag selection dialog confusing, because its positioning and shape is the same as the tags, so I initially thought it was a selected tag or something. It would be clearer if the button was positioned differently or more prominent like you have it on the questions dialog
2. The reset button on the questions dialog resets both the questions and the tags - so it should probably be outside the question dialog, for example, on the same row as the Tags and Questions button, aligned to the right

Thanks!

2020-10-29 22:27 UTC, avishkar58 commented
Hey Jean, maybe I was imagining, but didn't you previously have the ability to click on the reponse_id and it takes you to the responsePage? That seems to have disappeared?

2020-10-30 05:24 UTC, greeffjean commented on webapp/src/pages/ResponseList/components/ResponseListForm.js
> +        tagList.list().then(response => {
Oh yes, again here I made an update in a later issue, made a merge but I see the **tagList.service.js** was not updated in accordance.

2020-10-30 05:27 UTC, greeffjean commented on webapp/src/pages/ResponseList/components/ResponseListForm.js
> +        let list = this.state.selectedTags;
Thanks!

2020-10-30 09:06 UTC, greeffjean commented
> Hey Jean, maybe I was imagining, but didn't you previously have the ability to click on the reponse_id and it takes you to the responsePage? That seems to have disappeared?

` // Create Response Id Link
                if (this.props.event) {
                    val.response_id = <NavLink
                        to={`${this.props.event.key}/responsePage/${val.response_id}`}
                        className="table-nav-link"
                    >
                        {val.response_id}
                    </NavLink>;
                }`

Whats suppose to be happening here is the link you saw before only renders if the there is an event prop present in this component, since we need to write this line of code: `to={`${this.props.event.key}/responsePage/${val.response_id}`}`
the application breaks on my end because like I said in another PR, the props aren't set when Im building and testing.

Because I am navigating to this component via the browser url `http://localhost:8080/responseList` there are no props.

2020-10-30 09:44 UTC, greeffjean commented
> Hi Jean,
> 
> Great work! I really like what you did with the tag selection UI! Two suggestions to improve the UI a bit:
> 
> 1. I initially found the Update button on the tag selection dialog confusing, because its positioning and shape is the same as the tags, so I initially thought it was a selected tag or something. It would be clearer if the button was positioned differently or more prominent like you have it on the questions dialog
> 2. The reset button on the questions dialog resets both the questions and the tags - so it should probably be outside the question dialog, for example, on the same row as the Tags and Questions button, aligned to the right
> 
> Thanks!

Please see new UI updates, I think this new design is better

2020-10-30 10:39 UTC, greeffjean commented
> Hey Jean, maybe I was imagining, but didn't you previously have the ability to click on the reponse_id and it takes you to the responsePage? That seems to have disappeared?

I found the issue, there was a missing event prop that was not being passed down

2020-10-31 18:05 UTC, avishkar58 commented
Updated UI looks great thanks!
You must have forgotten to commit some renames again, this time both the responseList.service and tagList.service, I pushed a quick fix though

2020-10-31 18:05 UTC, avishkar58 approved these changes

2020-10-31 18:43 UTC, merged